name: DebugTest
on:
  push:
    branches: [ debug ]
  pull_request:
    branches: [ debug ]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        browser: [webkit, firefox]
        go: ['stable', 'oldstable']
    runs-on: ${{ matrix.os }}
    name:  ${{ matrix.browser }} on ${{ matrix.os }}, go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Cache drivers
      uses: actions/cache@v4
      with:
        # In order:
        # * Driver for linux
        # * Driver for macOS
        # * Driver for windows
        path: |
          ~/.cache/ms-playwright-go
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright-go
          ~/Library/Caches/ms-playwright
          ~\AppData\Local\ms-playwright-go
          ~\AppData\Local\ms-playwright
        key: ${{ runner.os }}-go${{ matrix.go }}-${{ matrix.browser }}-${{ hashFiles('**/run.go') }}
    - run: |
        go install ./...
        playwright install --with-deps ${{ matrix.browser }}
    - name: Test
      env:
        BROWSER: ${{ matrix.browser }}
        DEBUGP: '1'
      if: matrix.os == 'ubuntu-latest'
      run: xvfb-run go test -v -run "^(TestVideo)$" ./tests
    - name: Test
      env:
        BROWSER: ${{ matrix.browser }}
        DEBUGP: '1'
      if: matrix.os != 'ubuntu-latest'
      run: go test -v -run "^(TestVideo)$" ./tests